import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import astro from 'eslint-plugin-astro';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';

export default [
  {
    ignores: [
      '*.cjs',
      'node_modules/',
      'dist/',
      'dev-dist/',
      '.astro/',
      'build/',
      '.env',
      '.env.*',
      '!.env.example',
      'pnpm-lock.yaml',
      'yarn.lock',
      // generated by Astro
      'src/env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...svelte.configs['flat/recommended'],
  ...astro.configs['flat/recommended'],
  prettierRecommended,
  {
    files: ['**/*.svelte'],
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        parser: tseslint.parser,
      },
    },
    rules: {
      // Bug in eslint-plugin-svelte@3.19.0: uses removed ESLint 10 API isSpaceBetweenTokens
      'svelte/no-reactive-functions': 'off',
      // integerInput in Number.svelte is a deliberate reactive bridge ($: integerInput = integer,
      // then mutated by controls). Fixing requires refactoring the full control flow; defer to runes migration.
      'svelte/no-reactive-reassign': 'off',
    },
  },
  {
    files: ['**/*.astro'],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // prettier-plugin-astro cannot parse partytown inline scripts
    files: ['src/components/app/GATag.astro'],
    rules: {
      'prettier/prettier': 'off',
    },
  },
  {
    // prettier-plugin-astro cannot parse IntersectionObserver callback syntax
    files: ['src/components/app/Title.astro'],
    rules: {
      'prettier/prettier': 'off',
    },
  },
  {
    // prettier-plugin-astro cannot parse virtual module imports
    files: ['src/components/app/PWA.astro'],
    rules: {
      'prettier/prettier': 'off',
    },
  },
  {
    languageOptions: {
      ecmaVersion: 2020,
    },
  },
];
